### ISSUE TITLE
missing a file

### ISSUE THREAD

**Issue by YuqingCai0316** [ZHEGG/miccai2023#4]
I'm trying to run predict.py. Where can I download labels_test_inaccessible.txt ? Could you share it 
with me?

**Comment by ZHEGG** [comment]
hello，you can check out the official MICCAI repository！

**Comment by YuqingCai0316** [comment]
I have downloaded all the other data, except this one. It seems to be sent to those of you who have registered for the competition. However, I roughly know what is in this file. I wrote one myself and it is now running. I tested the model with my own two patients data, and its inference results are correct.
